/**
 * Paystack Payment Integration Module
 * Mystic AI — Fortune Telling App
 *
 * Supports:
 *   - Single readings:    R29
 *   - Monthly subscription: R99
 *   - Annual subscription:  R799
 *
 * API Base: https://api.paystack.co
 * Auth:     Bearer <secret_key>
 */

import crypto from "node:crypto";

// ---------------------------------------------------------------------------
// Keys
// ---------------------------------------------------------------------------
const TEST_SECRET = "sk_test_c700fbcca87790b2951d0b343b4f88564ef7105f";
const TEST_PUBLIC = "pk_test_2c5306b2e15d20f1b6d24627cdb070ed4df4f9d7";
const LIVE_SECRET = "sk_live_321a1dae031d7cf087dfb0e4f2f806c6a22cc148";
const LIVE_PUBLIC = "pk_live_cb358fef56c2bdcbabbd9af1ec77f7d632c163d2";

const PAYSTACK_BASE = "https://api.paystack.co";

// ---------------------------------------------------------------------------
// Config helper — switches keys based on NODE_ENV
// ---------------------------------------------------------------------------
interface PaystackConfig {
  secretKey: string;
  publicKey: string;
}

function getConfig(): PaystackConfig {
  const isProduction = process.env.NODE_ENV === "production";
  return {
    secretKey: isProduction ? LIVE_SECRET : TEST_SECRET,
    publicKey: isProduction ? LIVE_PUBLIC : TEST_PUBLIC,
  };
}

// ---------------------------------------------------------------------------
// Generic Paystack API response wrapper
// ---------------------------------------------------------------------------
interface PaystackApiResponse<T> {
  status: boolean;
  message: string;
  data: T;
}

// ---------------------------------------------------------------------------
// Internal fetch helper — every call to Paystack goes through here
// ---------------------------------------------------------------------------
class PaystackError extends Error {
  constructor(
    message: string,
    public readonly statusCode?: number,
    public readonly paystackMessage?: string,
  ) {
    super(message);
    this.name = "PaystackError";
  }
}

async function paystackFetch<T>(
  path: string,
  options: Omit<RequestInit, "headers"> & { headers?: Record<string, string> } = {},
): Promise<T> {
  const { secretKey } = getConfig();
  const url = `${PAYSTACK_BASE}${path}`;

  const headers: Record<string, string> = {
    Authorization: `Bearer ${secretKey}`,
    "Content-Type": "application/json",
    ...(options.headers ?? {}),
  };

  let response: Response;
  try {
    response = await fetch(url, { ...options, headers });
  } catch (err: unknown) {
    throw new PaystackError(
      `Network error reaching Paystack: ${err instanceof Error ? err.message : String(err)}`,
    );
  }

  // Paystack may return an empty 200 for some DELETE / disable actions
  const bodyText = await response.text();
  let body: PaystackApiResponse<T>;
  if (bodyText) {
    try {
      body = JSON.parse(bodyText) as PaystackApiResponse<T>;
    } catch {
      throw new PaystackError(
        `Invalid JSON response from Paystack (HTTP ${response.status})`,
        response.status,
      );
    }
  } else {
    // Empty body — construct a minimal success shape
    body = { status: true, message: "OK", data: null as unknown as T };
  }

  if (!response.ok || !body.status) {
    throw new PaystackError(
      body.message || `Paystack API returned HTTP ${response.status}`,
      response.status,
      body.message,
    );
  }

  return body.data;
}

// ===========================================================================
// 1. INITIALIZE TRANSACTION
// ===========================================================================

export interface InitializeTransactionRequest {
  /** Amount in ZAR (Paystack expects kobo for NGN, but for ZAR it's the base unit — cents/100) */
  amount: number;
  email: string;
  /** URL to redirect to after payment (success / cancel handled by Paystack inline) */
  callbackUrl?: string;
  /** Optional custom reference. Auto-generated by Paystack if omitted. */
  reference?: string;
  /** Arbitrary metadata attached to the transaction */
  metadata?: Record<string, unknown>;
  /** Payment channels to restrict (e.g. ["card", "bank"]) */
  channels?: string[];
}

export interface InitializeTransactionData {
  authorization_url: string;
  access_code: string;
  reference: string;
}

/**
 * Initialize a Paystack transaction and return the authorization URL + reference.
 *
 * @param amount - Amount in ZAR cents (e.g. R29.00 = 2900, R99.00 = 9900)
 * @param email  - Customer email address
 * @param callbackUrl - URL to redirect after payment
 * @returns { authorization_url, access_code, reference }
 */
export async function initializePaystackTransaction(
  amount: number,
  email: string,
  callbackUrl?: string,
  metadata?: Record<string, unknown>,
): Promise<InitializeTransactionData> {
  const payload: Record<string, unknown> = {
    amount: Math.round(amount), // ensure integer cents
    email,
  };

  if (callbackUrl) {
    payload.callback_url = callbackUrl;
  }
  if (metadata) {
    payload.metadata = metadata;
  }

  return paystackFetch<InitializeTransactionData>("/transaction/initialize", {
    method: "POST",
    body: JSON.stringify(payload),
  });
}

// ===========================================================================
// 2. VERIFY TRANSACTION
// ===========================================================================

export type PaystackTransactionStatus =
  | "abandoned"
  | "failed"
  | "ongoing"
  | "pending"
  | "processing"
  | "queued"
  | "reversed"
  | "success";

export interface VerifyTransactionCustomer {
  id: number;
  first_name: string | null;
  last_name: string | null;
  email: string;
  customer_code: string;
  phone: string | null;
  metadata: Record<string, unknown> | null;
  risk_action: string;
}

export interface VerifyTransactionAuthorization {
  authorization_code: string;
  bin: string;
  last4: string;
  exp_month: string;
  exp_year: string;
  channel: string;
  card_type: string;
  bank: string;
  country_code: string;
  brand: string;
  reusable: boolean;
  signature: string;
  account_name: string | null;
}

export interface VerifyTransactionPlan {}

export interface VerifyTransactionSubaccount {}

export interface VerifyTransactionSplit {}

export interface VerifyTransactionLog {
  start_time: number;
  time_spent: number;
  attempts: number;
  errors: number;
  success: boolean;
  mobile: boolean;
  input: unknown[];
  history: Array<{
    type: string;
    message: string;
    time: number;
  }>;
}

export interface VerifyTransactionData {
  id: number;
  domain: string;
  status: PaystackTransactionStatus;
  reference: string;
  amount: number; // in kobo / cents
  message: string | null;
  gateway_response: string;
  paid_at: string | null;
  created_at: string;
  channel: string;
  currency: string;
  ip_address: string | null;
  metadata: Record<string, unknown> | null;
  fees_breakdown: unknown | null;
  log: VerifyTransactionLog | null;
  authorization: VerifyTransactionAuthorization | null;
  customer: VerifyTransactionCustomer;
  plan: VerifyTransactionPlan | null;
  subaccount: VerifyTransactionSubaccount | null;
  split: VerifyTransactionSplit | null;
  order_id: string | null;
  paidAt: string | null;
  requested_amount: number;
  pos_transaction_data: unknown | null;
  source: unknown | null;
  fees: number | null;
  fees_split: unknown | null;
  transaction_date: string;
  plan_object: Record<string, unknown>;
  subaccount_object: Record<string, unknown>;
}

/**
 * Verify a Paystack transaction by its reference.
 *
 * @param reference - The transaction reference to verify
 * @returns Full transaction data from Paystack
 */
export async function verifyPaystackTransaction(
  reference: string,
): Promise<VerifyTransactionData> {
  return paystackFetch<VerifyTransactionData>(
    `/transaction/verify/${encodeURIComponent(reference)}`,
    { method: "GET" },
  );
}

// ===========================================================================
// 3. WEBHOOK HANDLER
// ===========================================================================

export type PaystackWebhookEventType =
  | "charge.success"
  | "charge.failed"
  | "charge.dispute.create"
  | "charge.dispute.remind"
  | "subscription.create"
  | "subscription.disable"
  | "subscription.expiring_cards"
  | "subscription.not_renew"
  | "transfer.success"
  | "transfer.failed"
  | "transfer.reversed";

export interface PaystackWebhookEvent {
  event: PaystackWebhookEventType;
  data: VerifyTransactionData | Record<string, unknown>;
}

export interface WebhookProcessingResult {
  acknowledged: boolean;
  event: PaystackWebhookEventType;
  reference?: string;
  action: "processed" | "ignored" | "error";
  message: string;
}

/**
 * Validate the Paystack webhook signature (HMAC SHA-512).
 *
 * Paystack signs every webhook payload with your secret key.
 * The signature is sent in the `x-paystack-signature` HTTP header.
 *
 * @param rawBody  - The raw request body as a string (exactly as received)
 * @param signature - The value of the `x-paystack-signature` header
 * @returns true if the signature is valid
 */
export function validatePaystackWebhookSignature(
  rawBody: string,
  signature: string,
): boolean {
  const { secretKey } = getConfig();
  const computed = crypto
    .createHmac("sha512", secretKey)
    .update(rawBody)
    .digest("hex");
  return crypto.timingSafeEqual(
    Buffer.from(computed, "utf-8"),
    Buffer.from(signature, "utf-8"),
  );
}

/**
 * Process a Paystack webhook event.
 *
 * Handles:
 *   - charge.success       → payment completed for a single reading
 *   - subscription.create  → new recurring subscription activated
 *   - subscription.disable → subscription cancelled / expired
 *
 * All other events are acknowledged but ignored.
 *
 * @param rawBody   - Raw request body string (needed for signature validation)
 * @param signature - x-paystack-signature header value
 * @returns Processing result
 */
export async function handlePaystackWebhook(
  rawBody: string,
  signature: string,
): Promise<WebhookProcessingResult> {
  // --- 1. Validate signature ---
  if (!validatePaystackWebhookSignature(rawBody, signature)) {
    return {
      acknowledged: false,
      event: "charge.success" as PaystackWebhookEventType, // placeholder
      action: "error",
      message: "Invalid webhook signature",
    };
  }

  // --- 2. Parse the event ---
  let event: PaystackWebhookEvent;
  try {
    event = JSON.parse(rawBody) as PaystackWebhookEvent;
  } catch {
    return {
      acknowledged: false,
      event: "charge.success" as PaystackWebhookEventType,
      action: "error",
      message: "Failed to parse webhook body as JSON",
    };
  }

  const eventType = event.event;
  const reference =
    (event.data as VerifyTransactionData)?.reference ?? undefined;

  // --- 3. Route by event type ---
  switch (eventType) {
    case "charge.success": {
      // Single payment succeeded — e.g. a R29 reading was paid
      // TODO: link to your business logic (grant access, send email, etc.)
      return {
        acknowledged: true,
        event: eventType,
        reference,
        action: "processed",
        message: `Payment ${reference} succeeded`,
      };
    }

    case "subscription.create": {
      // New subscription created — R99 monthly or R799 annual
      return {
        acknowledged: true,
        event: eventType,
        reference,
        action: "processed",
        message: `Subscription created for ${reference}`,
      };
    }

    case "subscription.disable": {
      // Subscription disabled (cancelled, expired, non-payment)
      return {
        acknowledged: true,
        event: eventType,
        reference,
        action: "processed",
        message: `Subscription disabled for ${reference}`,
      };
    }

    default: {
      // Acknowledge but ignore other event types
      return {
        acknowledged: true,
        event: eventType,
        reference,
        action: "ignored",
        message: `Event type '${eventType}' acknowledged but not processed`,
      };
    }
  }
}

// ===========================================================================
// 4. SUBSCRIPTION PLAN CREATOR
// ===========================================================================

export type PaystackPlanInterval = "hourly" | "daily" | "weekly" | "monthly" | "quarterly" | "biannually" | "annually";

export interface CreatePlanRequest {
  /** Plan name shown to the customer */
  name: string;
  /** Amount in ZAR cents */
  amount: number;
  /** Billing interval */
  interval: PaystackPlanInterval;
  /** Optional description */
  description?: string;
  /** Optional invoice limit (number of invoices before expiry) */
  invoiceLimit?: number;
  /** Whether to send invoices via email */
  sendInvoices?: boolean;
  /** Whether to send SMS notifications */
  sendSms?: boolean;
  /** Currency (defaults to ZAR) */
  currency?: string;
}

export interface CreatePlanData {
  id: number;
  name: string;
  plan_code: string;
  description: string | null;
  amount: number;
  interval: PaystackPlanInterval;
  send_invoices: boolean;
  send_sms: boolean;
  currency: string;
  invoice_limit: number;
  createdAt: string;
  updatedAt: string;
}

/**
 * Create a Paystack subscription plan.
 *
 * Mystic AI plans:
 *   - "Mystic Monthly"  — 9900  (R99.00 monthly)
 *   - "Mystic Annual"   — 79900 (R799.00 annually)
 *
 * @returns Created plan data including the plan_code needed for subscriptions
 */
export async function createPaystackPlan(
  params: CreatePlanRequest,
): Promise<CreatePlanData> {
  const payload: Record<string, unknown> = {
    name: params.name,
    amount: Math.round(params.amount),
    interval: params.interval,
    currency: params.currency || "ZAR",
  };

  if (params.description) {
    payload.description = params.description;
  }
  if (params.invoiceLimit !== undefined) {
    payload.invoice_limit = params.invoiceLimit;
  }
  if (params.sendInvoices !== undefined) {
    payload.send_invoices = params.sendInvoices;
  }
  if (params.sendSms !== undefined) {
    payload.send_sms = params.sendSms;
  }

  return paystackFetch<CreatePlanData>("/plan", {
    method: "POST",
    body: JSON.stringify(payload),
  });
}

// ===========================================================================
// Convenience: pre-configured Mystic AI plans
// ===========================================================================

export const MYSTIC_PLANS = {
  /** Single fortune reading — R29.00 */
  singleReading: { amount: 2900, description: "Single fortune reading" },
  /** Monthly subscription — R99.00 */
  monthlySubscription: {
    amount: 9900,
    interval: "monthly" as const,
    name: "Mystic Monthly",
    description: "Unlimited fortune readings — monthly",
  },
  /** Annual subscription — R799.00 */
  annualSubscription: {
    amount: 79900,
    interval: "annually" as const,
    name: "Mystic Annual",
    description: "Unlimited fortune readings — annual (save 33%)",
  },
} as const;

// ===========================================================================
// Re-exports for convenience
// ===========================================================================

export { getConfig, PaystackError, paystackFetch };
